export interface TaskTemplate {
  id: string;
  category: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'education' | 'inspection' | 'report' | 'admin';
  categoryLabel: string;
  title: string;
  scope: string;
  description: string;
  defaultPriority: 'low' | 'normal' | 'high' | 'urgent';
  /** 기본 소요 시간(시간 단위). 기한 자동 계산에 사용 */
  defaultDurationHours?: number;
}

export const TASK_CATEGORIES: { key: TaskTemplate['category']; label: string; icon: string }[] = [
  { key: 'daily',      label: '매일 반복',    icon: '☀️' },
  { key: 'weekly',     label: '주간 반복',    icon: '📅' },
  { key: 'monthly',    label: '월간 반복',    icon: '🗓️' },
  { key: 'quarterly',  label: '분기·연간',    icon: '📊' },
  { key: 'education',  label: '교육·훈련',    icon: '📚' },
  { key: 'inspection', label: '점검·관리',    icon: '🔍' },
  { key: 'report',     label: '보고·정산',    icon: '📋' },
  { key: 'admin',      label: '행정·서무',    icon: '🗂️' },
];

export const TASK_TEMPLATES: TaskTemplate[] = [
  // ── 매일 반복 ───────────────────────────────────────────────────────────
  {
    id: 'daily_store_clean',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: '매장 청소',
    scope: '매장 전체 (영업장, 창고, 화장실, 출입구)',
    description: `[청소 범위]\n- 영업장 바닥 쓸기·걸레질\n- 테이블·의자 닦기\n- 화장실 청소 및 소독\n- 창고 정리정돈\n- 출입구 및 유리창 닦기\n\n[완료 기준]\n청소 완료 후 사진 촬영하여 보고`,
    defaultPriority: 'normal',
    defaultDurationHours: 1,
  },
  {
    id: 'daily_closing',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: '마감 정리',
    scope: '매장 전체',
    description: `[마감 절차]\n- 현금 시재 확인 및 금고 입금\n- 전자기기(조명, 냉난방, 포스기) 전원 차단\n- 출입문 잠금 확인\n- 가스·수도 밸브 잠금\n- 이상 사항 일지 작성\n\n[완료 기준]\n마감 체크리스트 항목 전체 완료`,
    defaultPriority: 'high',
    defaultDurationHours: 1,
  },
  {
    id: 'daily_inventory_check',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: '일일 재고 확인',
    scope: '재고 창고 및 판매대',
    description: `[확인 항목]\n- 주요 상품 재고 수량 파악\n- 부족 품목 재발주 목록 작성\n- 유통기한 임박 제품 분리\n- 재고 대장 업데이트\n\n[완료 기준]\n재고 현황을 시스템에 입력 후 이상 없음 확인`,
    defaultPriority: 'normal',
    defaultDurationHours: 1,
  },
  {
    id: 'daily_sales_report',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: '일일 매출 정산',
    scope: '영업 전체',
    description: `[정산 항목]\n- POS 일일 매출 마감 출력\n- 현금·카드·배달앱 매출 대조\n- 오차 발생 시 원인 파악 및 기록\n- 정산 자료 관리자 공유\n\n[완료 기준]\n정산 시트 작성 완료 및 공유`,
    defaultPriority: 'high',
    defaultDurationHours: 1,
  },
  {
    id: 'daily_opening',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: '개점 준비',
    scope: '매장 전체',
    description: `[개점 절차]\n- 전원 및 조명 점등\n- 포스·결제 단말기 정상 작동 확인\n- 진열 상품 정렬 및 보충\n- 청결 상태 최종 점검\n- 간판·현수막 위치 확인\n\n[완료 기준]\n개점 체크리스트 완료`,
    defaultPriority: 'high',
    defaultDurationHours: 1,
  },
  {
    id: 'daily_sns_upload',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: 'SNS 콘텐츠 업로드',
    scope: '공식 SNS 채널 (인스타그램, 네이버 등)',
    description: `[업무 내용]\n- 당일 업로드 콘텐츠 최종 확인\n- 해시태그·문구 검토\n- 게시글 업로드 및 예약\n- 이전 게시물 댓글 응대\n\n[완료 기준]\n업로드 링크 공유`,
    defaultPriority: 'normal',
    defaultDurationHours: 1,
  },
  {
    id: 'daily_safety_check',
    category: 'daily',
    categoryLabel: '매일 반복',
    title: '소방·안전 일일 점검',
    scope: '사업장 전체',
    description: `[점검 항목]\n- 소화기 위치 및 상태 확인\n- 비상구 장애물 여부 점검\n- 가스 누출 여부 확인\n- 전기 과부하 기기 점검\n\n[완료 기준]\n점검표 서명 후 관리자 보고`,
    defaultPriority: 'normal',
    defaultDurationHours: 1,
  },

  // ── 주간 반복 ───────────────────────────────────────────────────────────
  {
    id: 'weekly_meeting',
    category: 'weekly',
    categoryLabel: '주간 반복',
    title: '주간 팀 회의',
    scope: '팀 전체',
    description: `[회의 안건]\n- 지난 주 업무 진척 보고\n- 이번 주 주요 일정 공유\n- 이슈 사항 논의 및 해결책 도출\n- 담당자별 업무 분장 확인\n\n[준비 사항]\n회의 전까지 개인 주간 업무 보고서 작성`,
    defaultPriority: 'high',
    defaultDurationHours: 2,
  },
  {
    id: 'weekly_report',
    category: 'weekly',
    categoryLabel: '주간 반복',
    title: '주간 업무 보고서 제출',
    scope: '담당 업무 전체',
    description: `[보고 내용]\n- 완료된 업무 목록\n- 진행 중 업무 진척도 (%)\n- 다음 주 계획\n- 지원이 필요한 사항\n\n[제출 방식]\n시스템 보고 기능 사용, 마감: 금요일 17시`,
    defaultPriority: 'normal',
    defaultDurationHours: 1,
  },
  {
    id: 'weekly_order',
    category: 'weekly',
    categoryLabel: '주간 반복',
    title: '주간 발주',
    scope: '소모품 및 판매 상품 전체',
    description: `[발주 절차]\n- 재고 현황 파악\n- 발주 필요 품목 목록 작성\n- 거래처별 주문서 작성\n- 발주 완료 후 예상 입고일 확인\n\n[완료 기준]\n발주서 결재 완료 및 거래처 전송`,
    defaultPriority: 'high',
    defaultDurationHours: 2,
  },
  {
    id: 'weekly_inventory',
    category: 'weekly',
    categoryLabel: '주간 반복',
    title: '주간 재고 실사',
    scope: '창고 및 판매대 전체',
    description: `[실사 절차]\n- 품목별 현물 재고 수량 카운트\n- 시스템 재고와 대조 및 차이 기록\n- 오차 원인 파악\n- 재고 대장 업데이트\n\n[완료 기준]\n실사 결과 보고서 제출`,
    defaultPriority: 'normal',
    defaultDurationHours: 3,
  },
  {
    id: 'weekly_deep_clean',
    category: 'weekly',
    categoryLabel: '주간 반복',
    title: '주간 대청소',
    scope: '매장 전체 (구석·집기류 포함)',
    description: `[청소 항목]\n- 에어컨 필터 청소\n- 냉장·냉동고 내부 정리\n- 선반·집기류 세척\n- 창문·외벽 청소\n- 배수구 청소\n\n[완료 기준]\n대청소 완료 사진 보고`,
    defaultPriority: 'normal',
    defaultDurationHours: 3,
  },
  {
    id: 'weekly_customer_feedback',
    category: 'weekly',
    categoryLabel: '주간 반복',
    title: '고객 리뷰 모니터링',
    scope: '주요 플랫폼 (네이버, 카카오, 배달앱 등)',
    description: `[모니터링 항목]\n- 신규 리뷰 확인 및 정리\n- 부정 리뷰 원인 분석\n- 개선 사항 도출\n- 답글 작성 및 등록\n\n[완료 기준]\n리뷰 현황 요약 보고`,
    defaultPriority: 'normal',
    defaultDurationHours: 1,
  },

  // ── 월간 반복 ───────────────────────────────────────────────────────────
  {
    id: 'monthly_meeting',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '월간 전체 회의',
    scope: '전 직원',
    description: `[회의 안건]\n- 월간 경영 성과 공유\n- 부서별 월간 실적 보고\n- 다음 달 주요 계획 발표\n- 포상 및 공지사항\n\n[준비 사항]\n팀장 이상: 부서별 실적 자료 사전 제출`,
    defaultPriority: 'high',
    defaultDurationHours: 3,
  },
  {
    id: 'monthly_sales_report',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '월간 실적 보고서 작성',
    scope: '담당 영역 전체',
    description: `[보고 내용]\n- 월간 매출·비용 현황\n- 목표 대비 달성률\n- 주요 이슈 및 개선 사항\n- 다음 달 계획\n\n[제출 기한]\n매월 말일 17시까지`,
    defaultPriority: 'high',
    defaultDurationHours: 4,
  },
  {
    id: 'monthly_payroll_review',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '급여 명세서 확인 및 배포',
    scope: '전 직원',
    description: `[업무 내용]\n- 근태 데이터 최종 확인\n- 급여 계산 검토\n- 명세서 발송\n- 이의신청 접수 및 처리\n\n[완료 기준]\n전 직원 급여 지급 완료`,
    defaultPriority: 'urgent',
    defaultDurationHours: 4,
  },
  {
    id: 'monthly_inventory_full',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '월간 전체 재고 정리',
    scope: '창고·판매장 전체 품목',
    description: `[업무 내용]\n- 전 품목 재고 실사\n- 불용 재고 처리 계획 수립\n- 발주 계획 수립\n- 재고 대장 최종 정리\n\n[완료 기준]\n재고 정리 보고서 제출`,
    defaultPriority: 'normal',
    defaultDurationHours: 6,
  },
  {
    id: 'monthly_marketing_plan',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '월간 마케팅 계획 수립',
    scope: '마케팅팀 / 담당자',
    description: `[계획 항목]\n- 이달 주요 프로모션 기획\n- SNS·광고 캘린더 작성\n- 예산 배분 계획\n- 지난 달 성과 분석 반영\n\n[완료 기준]\n월간 마케팅 계획서 최종 제출`,
    defaultPriority: 'high',
    defaultDurationHours: 4,
  },
  {
    id: 'monthly_tax_invoice',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '세금계산서 발행·정리',
    scope: '경리·회계 담당자',
    description: `[업무 내용]\n- 전월 거래처별 세금계산서 발행\n- 수취 세금계산서 수집 및 정리\n- 부가세 신고 자료 준비\n- 계산서 보관 (전자 및 실물)\n\n[완료 기준]\n세금계산서 발행 목록 제출`,
    defaultPriority: 'urgent',
    defaultDurationHours: 3,
  },
  {
    id: 'monthly_equipment_maintenance',
    category: 'monthly',
    categoryLabel: '월간 반복',
    title: '설비·장비 월간 점검',
    scope: '사업장 내 전 설비',
    description: `[점검 항목]\n- 주요 장비 작동 상태 점검\n- 소모품(필터, 부품) 교체 여부 확인\n- 이상 설비 수리 요청\n- 점검 일지 작성\n\n[완료 기준]\n점검표 서명 후 보고`,
    defaultPriority: 'normal',
    defaultDurationHours: 3,
  },

  // ── 분기·연간 ───────────────────────────────────────────────────────────
  {
    id: 'quarterly_review',
    category: 'quarterly',
    categoryLabel: '분기·연간',
    title: '분기 성과 리뷰',
    scope: '팀 전체',
    description: `[리뷰 항목]\n- 분기 목표 대비 달성률 분석\n- KPI 지표 점검\n- 우수 사례 및 개선 필요 사항 도출\n- 다음 분기 목표 설정\n\n[완료 기준]\n분기 리뷰 보고서 공유`,
    defaultPriority: 'high',
    defaultDurationHours: 4,
  },
  {
    id: 'annual_plan',
    category: 'quarterly',
    categoryLabel: '분기·연간',
    title: '연간 사업계획 수립',
    scope: '경영진 및 팀장',
    description: `[계획 항목]\n- 연간 매출·비용 목표 수립\n- 사업 전략 및 핵심 과제 선정\n- 부서별 목표 배분\n- 예산 편성\n\n[완료 기준]\n경영진 승인 후 전 직원 공유`,
    defaultPriority: 'urgent',
    defaultDurationHours: 8,
  },
  {
    id: 'quarterly_safety_inspection',
    category: 'quarterly',
    categoryLabel: '분기·연간',
    title: '분기 안전 점검',
    scope: '사업장 전체',
    description: `[점검 항목]\n- 소방 설비 점검\n- 전기 안전 점검\n- 화학물질 보관 상태 확인\n- 안전 교육 이수 현황 점검\n\n[완료 기준]\n안전 점검 보고서 제출 및 조치 완료`,
    defaultPriority: 'high',
    defaultDurationHours: 4,
  },
  {
    id: 'annual_hr_evaluation',
    category: 'quarterly',
    categoryLabel: '분기·연간',
    title: '연간 직원 성과 평가',
    scope: '전 직원',
    description: `[평가 절차]\n- 자기 평가서 작성\n- 상사 평가 진행\n- 면담 및 피드백\n- 평가 결과 반영 (승진·급여 조정)\n\n[완료 기준]\n전 직원 평가 완료 및 결과 통보`,
    defaultPriority: 'high',
    defaultDurationHours: 8,
  },

  // ── 교육·훈련 ───────────────────────────────────────────────────────────
  {
    id: 'edu_onboarding',
    category: 'education',
    categoryLabel: '교육·훈련',
    title: '신입 직원 온보딩 교육',
    scope: '신입 입사자',
    description: `[교육 내용]\n- 회사 소개 및 조직도 안내\n- 사내 규정·복리후생 안내\n- 업무 시스템 사용법\n- 담당 업무 현장 OJT\n\n[완료 기준]\n온보딩 체크리스트 완료 및 서명`,
    defaultPriority: 'high',
    defaultDurationHours: 8,
  },
  {
    id: 'edu_job_training',
    category: 'education',
    categoryLabel: '교육·훈련',
    title: '직무 역량 교육',
    scope: '해당 직군 전체',
    description: `[교육 내용]\n- 교육 주제: (지시자가 구체적으로 기재)\n- 교육 방식: 집합 교육 / 온라인 / OJT\n- 교육 시간: (지시자 기재)\n\n[완료 기준]\n교육 수료 확인증 제출 또는 담당자 서명`,
    defaultPriority: 'normal',
    defaultDurationHours: 4,
  },
  {
    id: 'edu_safety',
    category: 'education',
    categoryLabel: '교육·훈련',
    title: '산업 안전 교육',
    scope: '전 직원 (법정 의무)',
    description: `[교육 내용]\n- 산업재해 예방\n- 비상대피 요령\n- 화재 예방 및 초기 대응\n- 위험 물질 취급 안전 수칙\n\n[법정 기준]\n월 1회 이상 (산업안전보건법 제29조)\n[완료 기준]\n교육 서명부 보관`,
    defaultPriority: 'high',
    defaultDurationHours: 2,
  },
  {
    id: 'edu_cs',
    category: 'education',
    categoryLabel: '교육·훈련',
    title: '고객 응대(CS) 교육',
    scope: '고객 접점 직원',
    description: `[교육 내용]\n- 서비스 마인드 및 태도\n- 고객 불만 처리 절차\n- 전화·대면 응대 스크립트\n- 실습 및 롤플레이\n\n[완료 기준]\n교육 평가 점수 기준 이상`,
    defaultPriority: 'normal',
    defaultDurationHours: 3,
  },

  // ── 점검·관리 ───────────────────────────────────────────────────────────
  {
    id: 'inspect_equipment',
    category: 'inspection',
    categoryLabel: '점검·관리',
    title: '주요 장비 정기 점검',
    scope: '생산·영업 주요 장비',
    description: `[점검 항목]\n- 장비 작동 상태 테스트\n- 오일·냉각수 등 소모품 확인\n- 이상 소음·진동 여부 확인\n- 교체 부품 및 수리 내역 기록\n\n[완료 기준]\n점검 일지 작성 완료`,
    defaultPriority: 'normal',
    defaultDurationHours: 2,
  },
  {
    id: 'inspect_facility',
    category: 'inspection',
    categoryLabel: '점검·관리',
    title: '시설 안전 정기 점검',
    scope: '건물·시설 전체',
    description: `[점검 항목]\n- 전기 배선·콘센트 과열 여부\n- 배관·누수 여부\n- 건물 균열·파손 여부\n- 출입구·계단 안전 상태\n\n[완료 기준]\n점검 보고서 제출 및 이상 사항 조치`,
    defaultPriority: 'high',
    defaultDurationHours: 3,
  },
  {
    id: 'inspect_data_backup',
    category: 'inspection',
    categoryLabel: '점검·관리',
    title: '데이터 백업 확인',
    scope: '서버·시스템 담당자',
    description: `[확인 항목]\n- 자동 백업 정상 완료 여부\n- 백업 파일 무결성 확인\n- 복원 테스트 (월 1회)\n- 백업 보관 기한 준수 여부\n\n[완료 기준]\n백업 확인 보고서 제출`,
    defaultPriority: 'high',
    defaultDurationHours: 1,
  },

  // ── 보고·정산 ───────────────────────────────────────────────────────────
  {
    id: 'report_competitor',
    category: 'report',
    categoryLabel: '보고·정산',
    title: '경쟁사 모니터링 보고',
    scope: '마케팅·영업팀',
    description: `[모니터링 항목]\n- 경쟁사 신규 상품·서비스 동향\n- 가격 정책 변화\n- SNS·광고 전략 분석\n- 시장 트렌드 요약\n\n[완료 기준]\n경쟁사 분석 보고서 제출`,
    defaultPriority: 'normal',
    defaultDurationHours: 3,
  },
  {
    id: 'report_customer_satisfaction',
    category: 'report',
    categoryLabel: '보고·정산',
    title: '고객 만족도 조사·분석',
    scope: '고객 전체 (설문 대상)',
    description: `[업무 내용]\n- 설문 문항 설계 또는 기존 양식 활용\n- 설문 배포 (문자·앱·현장)\n- 결과 집계 및 분석\n- 개선 사항 도출 및 보고\n\n[완료 기준]\n고객 만족도 보고서 제출`,
    defaultPriority: 'normal',
    defaultDurationHours: 4,
  },
  {
    id: 'report_homepage_update',
    category: 'report',
    categoryLabel: '보고·정산',
    title: '홈페이지·앱 콘텐츠 업데이트',
    scope: '공식 채널 담당자',
    description: `[업데이트 내용]\n- 이달 공지사항·이벤트 등록\n- 상품·서비스 정보 최신화\n- 연락처·영업시간 정확성 확인\n- SEO 키워드 검토\n\n[완료 기준]\n업데이트 화면 캡처 보고`,
    defaultPriority: 'normal',
    defaultDurationHours: 2,
  },

  // ── 행정·서무 ───────────────────────────────────────────────────────────
  {
    id: 'admin_vacation_review',
    category: 'admin',
    categoryLabel: '행정·서무',
    title: '연차·휴가 사용 현황 점검',
    scope: '전 직원',
    description: `[업무 내용]\n- 직원별 연차 잔여 현황 확인\n- 소진 촉진 대상자 안내\n- 연차 사용 계획 수립 지원\n- 인사 시스템 데이터 정합성 확인\n\n[완료 기준]\n현황 보고서 제출`,
    defaultPriority: 'normal',
    defaultDurationHours: 2,
  },
  {
    id: 'admin_contract_review',
    category: 'admin',
    categoryLabel: '행정·서무',
    title: '계약서·문서 정기 검토',
    scope: '경영지원·총무 담당자',
    description: `[업무 내용]\n- 만료 임박 계약 확인 (임대차, 용역, 거래처)\n- 갱신 또는 종료 의사 결정\n- 계약서 보관 현황 점검\n- 필요 서류 준비\n\n[완료 기준]\n계약 현황 보고서 및 갱신 처리 완료`,
    defaultPriority: 'high',
    defaultDurationHours: 3,
  },
];
